version: '3.8'

services:
  phone-usage-reporter:
    build: .
    container_name: phone-usage-reporter
    ports:
      - "${PORT:-4600}:${PORT:-4600}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-4600}
      - API_KEY=${API_KEY}
      - CRON_SCHEDULE=${CRON_SCHEDULE:-0 9 * * 1}
      - HOURLY_CRON_SCHEDULE=${HOURLY_CRON_SCHEDULE:-55 * * * *}
      - DAILY_CRON_SCHEDULE=${DAILY_CRON_SCHEDULE:-0 0 * * *}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # 追加: エンコーディング設定
      - LANG=ja_JP.UTF-8
      - LC_ALL=ja_JP.UTF-8
      - TZ=Asia/Tokyo
      # Supabase関連設定
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SUPABASE_STORAGE_BUCKET=${SUPABASE_STORAGE_BUCKET}
      # Slack関連設定
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    volumes:
      - ./logs:/app/logs
      - ./tmp:/app/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-4600}/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # 本番環境では常にログを保存
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"